version: '3.8'

services:
  springboot-app:
    image: openjdk:17
    container_name: prod
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/toy?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "1000:8080"
    depends_on:
      - db
    networks:
      - prod

  db:
    image: mariadb:latest
    container_name: mariadb_prod
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: toy
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "2345:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - prod
volumes:
  mariadb_data:

networks:
  prod:
    driver: bridge
