version: '3.8'

services:
  database:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: toy
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "1234:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - toy
volumes:
  mariadb_data:

networks:
  toy:
    driver: bridge
